### Submit Orders
POST http://localhost:8080/odata/v4/teamcenter/Bolle
Content-Type: application/json

[{ 
    "Bolla" : "4ABolla",
    "PartNumber" : "Parte1",
    "Odl" : "890"
},
{ 
    "Bolla" : "5ABolla",
    "PartNumber" : "Parte1",
    "Odl" : "890"
}
]


###  Se si vogliono fare più operazioni vanno separate dai 3 cancelletti ###
GET  http://localhost:8080/odata/v4/teamcenter/Bolle


###  
GET  http://localhost:4004/fammivedere/Books?$expand=author
