---
spring:
    config.activate.on-profile: default
    datasource:
        url: "jdbc:sqlite:/home/user/projects/TeamCenter/sqlite.db"
        driver-class-name: org.sqlite.JDBC
        initialization-mode: never
        hikari:
            maximum-pool-size: 1 
    security:
        user:
            name: gyo
            password: gyo


server:
  port: 8085

#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/xxx_db
#    username: root
#    password: root


    
